'use strict';var hx={TAB:0,sj:1,Im:2},ix=function(a){yb("MediaRouter.CastStreaming.Start.Success",a,hx)};var jx=db("mr.mirror.cast.LogUploader"),lx=function(a,b,c){kx("raw_events.log.gz",a,b,c);return b?"https://crash.corp.google.com/samples?reportid=&q="+encodeURIComponent("UserComments='"+b+"'"):""},kx=function(a,b,c,d){if(0==b.size)jx.info("Trying to upload an empty file to Crash"),d&&d(null);else{var e=new FormData;e.append("prod","Cast");e.append("ver",chrome.runtime.getManifest().version);e.append(a,b);c&&e.append("comments",c);Lu("https://clients2.google.com/cr/report",function(a){a=a.target;
var b=null;Vu(a)?(b=Wu(a),jx.info("Upload to Crash succeeded: "+b)):jx.info("Upload to Crash failed. HTTP status: "+a.Ja());d&&d(b)},"POST",e,void 0,3E4)}};var mx=function(){this.b=0;ej(this)},ox=function(){nx||(nx=new mx);return nx},px=function(){var a=ox(),b={fraction:.01,autoSubmitTimeLimitMillis:6048E5},c=b.autoSubmitTimeLimitMillis,d=Date.now();return a.b&&c&&d-a.b<c?!1:Math.random()<b.fraction};mx.prototype.ya=function(){return"mirror.cast.LogUtils"};mx.prototype.eb=function(){return[void 0,{lastAutoSubmitMillis:this.b}]};mx.prototype.cb=function(){var a=cj(this);this.b=a&&a.lastAutoSubmitMillis||0};var nx=null;db("mr.mirror.cast.LogUtils");var qx={Wu:"OFFER",ur:"ANSWER",uv:"PRESENTATION",ct:"GET_STATUS",rw:"STATUS_RESPONSE",bt:"GET_CAPABILITIES",Qr:"CAPABILITIES_RESPONSE",Vv:"RPC"};var rx=function(){this.capabilities=this.status=this.b=this.error=this.rpc=this.result=this.type=this.f=this.sessionId=null},ux=function(a){try{if("string"!==typeof a)throw SyntaxError("Cannot parse non-string as JSON");var b;sx(JSON.parse(a),function(a){b=tx(a)},function(){throw Error("non-Object result from JSON parse");});return b}catch(d){var c=d instanceof SyntaxError?"JSON parse error: "+d.message:"Type coercion error: "+d.message}"string"==typeof a?a="a string: "+a:a instanceof ArrayBuffer?
(a=new Uint8Array(a),a="an ArrayBuffer whose base64 is "+btoa(String.fromCharCode.apply(null,a))):a="of invalid data type "+typeof a;throw Error(c+". Input was "+a);},tx=function(a){var b=new rx;null!=a.sessionId&&(b.sessionId=String(a.sessionId));vx(a.seqNum,function(a){b.f=a},function(){throw Error('"seqNum" must be a number');});if("type"in a){for(var c=String(a.type).toUpperCase(),d=k(Object.keys(qx)),e=d.next();!e.done;e=d.next())if(qx[e.value]==c){b.type=c;break}if(!b.type)throw Error('not a known message "type"');
}"result"in a&&(b.result=String(a.result));if("rpc"in a){if("string"!==typeof a.rpc)throw Error('"rpc" must be a String containing a base64 payload');b.rpc=new Uint8Array([].concat(n(atob(a.rpc))).map(function(a){return a.charCodeAt(0)}))}sx(a.error,function(a){b.error=wx(a)},function(){throw Error('"error" must be an Object');});sx(a.answer,function(a){b.b=xx(a)},function(){throw Error('"answer" must be an Object');});sx(a.status,function(a){b.status=yx(a)},function(){throw Error('"status" must be an Object');
});sx(a.capabilities,function(a){b.capabilities=zx(a)},function(){throw Error('"capabilities" must be an Object');});return b},sx=function(a,b,c){void 0!==a&&(a instanceof Object?b(a):c())},vx=function(a,b,c){void 0!==a&&("number"!==typeof a?c():b(a))},Ax=function(a,b,c){void 0!==a&&(a instanceof Array&&a.every(function(a){return"number"===typeof a})?b(a):c())},Bx=function(a,b,c){void 0!==a&&(a instanceof Array?b(a.map(function(a){return String(a)})):c())},Cx=function(){this.j=null;this.b=[];this.f=
[];this.h=this.g=this.l=null},xx=function(a){var b=new Cx;vx(a.udpPort,function(a){b.j=a},function(){throw Error('"answer.udpPort" must be a number');});Ax(a.sendIndexes,function(a){b.b=a},function(){throw Error('"answer.sendIndexes" must be an array of numbers');});Ax(a.ssrcs,function(a){b.f=a},function(){throw Error('"answer.ssrcs" must be an array of numbers');});"IV"in a&&(b.l=String(a.IV));"receiverGetStatus"in a&&(b.g="true"==String(a.receiverGetStatus).toLowerCase());"castMode"in a&&(b.h=String(a.castMode));
return b},Dx=function(){this.details=this.description=this.code=null},wx=function(a){var b=new Dx;vx(a.code,function(a){b.code=a},function(){throw Error('"error.code" must be a number');});"description"in a&&(b.description=String(a.description));sx(a.details,function(a){b.details=a},function(){throw Error('"error.details" must be an Object');});return b},Ex=function(){this.f=this.b=null},yx=function(a){var b=new Ex;vx(a.wifiSnr,function(a){b.b=a},function(){throw Error('"status.wifiSnr" must be a number');
});Ax(a.wifiSpeed,function(a){b.f=a},function(){throw Error('"status.wifiSpeed" must be an array of numbers');});return b},Fx=function(){this.f=this.b=null},zx=function(a){var b=new Fx;Bx(a.mediaCaps,function(a){b.b=a},function(){throw Error('"capabilities.mediaCaps" must be an array');});if("keySystems"in a){a=a.keySystems;if(!(a instanceof Array))throw Error('"capabilities.keySystems" must be an array');b.f=a.map(function(a){var b;sx(a,function(a){b=Gx(a)},function(){throw Error('"capabilities.keySystems" entries must be *Objects');
});return b})}return b},Hx=function(){this.h=this.w=this.l=this.j=this.u=this.b=this.o=this.f=this.initDataTypes=this.g=null},Gx=function(a){var b=new Hx;"keySystemName"in a&&(b.g=String(a.keySystemName));Bx(a.initDataTypes,function(a){b.initDataTypes=a},function(){throw Error('"capabilities.initDataTypes" must be an array');});Bx(a.codecs,function(a){b.f=a},function(){throw Error('"capabilities.codecs" must be an array');});Bx(a.secureCodecs,function(a){b.o=a},function(){throw Error('"capabilities.secureCodecs" must be an array');
});Bx(a.audioRobustness,function(a){b.b=a},function(){throw Error('"capabilities.audioRobustness" must be an array');});Bx(a.videoRobustness,function(a){b.u=a},function(){throw Error('"capabilities.videoRobustness" must be an array');});"persistentLicenseSessionSupport"in a&&(b.j=String(a.persistentLicenseSessionSupport));"persistentReleaseMessageSessionSupport"in a&&(b.l=String(a.persistentReleaseMessageSessionSupport));"persistentStateSupport"in a&&(b.w=String(a.persistentStateSupport));"distinctiveIdentifierSupport"in
a&&(b.h=String(a.distinctiveIdentifierSupport));return b};var Ix=function(a){this.m=db("mr.mirror.cast.MessageDispatcher");this.g=a;this.b=null;this.f=new Map;this.h=0},Jx=function(a,b,c){if(a.f.has(b))throw Error("Attempt to multiple-subscribe to the same response type: "+b);a.f.set(b,c);a.h=0;kb(a.m,"Added subscriber for "+b+"-type messages.");a.b||(a.b=fw(a.g),a.b.onMessage=a.j.bind(a))},Kx=function(a,b){a.f.delete(b)&&kb(a.m,function(){return"Removed subscriber of "+b+"-type messages."});0==a.f.size&&a.b&&(a.b.Ra(),a.b=null)};
Ix.prototype.sendMessage=function(a){return this.b?"RPC"==a.type?this.b.sendMessage(a,{namespace:"urn:x-cast:com.google.cast.remoting"}):this.b.sendMessage(a,{namespace:"urn:x-cast:com.google.cast.webrtc"}):Promise.reject(Error("Require at least one subscriber before sending messages."))};
var Lx=function(a,b,c,d,e){var f=null,h=function(){Kx(a,c);null!=f&&(clearTimeout(f),f=null)};try{Jx(a,c,function(a){e(a)&&h()})}catch(l){e(null,l);return}f=setTimeout(function(){h();e(null,Error("timeout"))},d);a.sendMessage(b).catch(function(a){h();e(null,a)})};
Ix.prototype.j=function(a){if(a&&"string"===typeof a.namespace_&&a.namespace_.startsWith("urn:x-cast:com.google.cast.")){do{var b=void 0;try{b=ux(a.data)}catch(d){b=d.message;break}if(b.type){var c=this.f.get(b.type);if(c)try{c(b);return}catch(d){b="Error thrown during delivery. Response was: "+(JSON.stringify(b)+". Error from subscriber callback ")+("was: "+d.message+".")}else b="Message was ignored: "+JSON.stringify(b)}else b="Message did not include response type: "+JSON.stringify(b)}while(0);
10>this.h?this.m.F(b):kb(this.m,b);++this.h}};var Mx=function(){this.b=Promise.resolve(1)},Ox=function(a,b,c){return Nx(a,function(a){return a==b},c)},Px=function(a,b){var c=[3,4];return Nx(a,function(a){return-1!=c.indexOf(a)},b)},Qx=function(a,b){a.b=a.b.catch(function(){return 1});return Nx(a,function(){return!0},b)},Nx=function(a,b,c){var d,e,f=new Promise(function(a,b){d=a;e=b});a.b=a.b.then(function(a){if(!b(a))return e(Error("Operation requires a different starting checkpoint than "+a)),Promise.resolve(a);var f=new Rx(a);try{var h=c(f)}catch(u){h=
Promise.reject(u)}return h.then(function(a){return d(a)},function(a){return e(a)}).then(function(){if(null===f.b)throw Error("A prior operation that started at "+(a+" did not complete."));return f.b})},function(a){e(a);throw a;});return f},Rx=function(a){this.f=a;this.b=null},Sx=function(a,b){a.b="number"===typeof b?b:a.f};var Tx=chrome.cast.streaming,Vx=function(a,b,c,d,e){this.H=a.sessionId;this.u=a.rg;this.ea=a.Ie;this.h=b;this.G=c;this.D=d;this.M=Ux(e,"onAnswer",this.u);this.Aa=Ux(e,"onSessionStop",this.u);this.m=db("mr.mirror.cast.StreamingLaunchWorkflow");this.B=new Mx;this.w=this.A=this.o=this.f=this.b=this.l=this.j=this.g=null};
Vx.prototype.start=function(a,b,c){var d=this;if(!a&&!b)return Promise.reject(Error("No tracks to stream"));var e=a instanceof Wx,f=b instanceof Wx;(e&&b&&!f||f&&a&&!e)&&Db("Mixing remoting and non-remoting tracks");return Ox(this.B,1,function(e){d.g=a;d.j=b;d.l=c;d.m.info(function(){return"Launching streaming for "+Xx(d)+" "+("to a "+d.ea+".")});return Yx(d).then(d.C.bind(d)).then(function(a){return Zx(d,a).then(function(b){d.M();var c=$x(d,b,a);d.b=ay(d,d.b,c);d.f=ay(d,d.f,c);if(!d.b&&!d.f)throw Error("Receiver did not select any offers from: "+
JSON.stringify(a));d.A=!!b.g;d.w=function(a,b){a==d.b?d.l.Be("Audio stream (id="+a+") error: "+b):a==d.f&&d.l.Be("Video stream (id="+a+") error: "+b)};Tx.rtpStream.onError.addListener(d.w);return by(d,b,c)})}).then(function(){d.m.info(function(){return"Launched streaming for "+Xx(d)});d.l.Pf(d);Sx(e,2);return{Zn:d.b,Sq:d.f}})})};
Vx.prototype.stop=function(){var a=this;return Qx(this.B,function(b){if(!a.g&&!a.j)return Sx(b,1),Promise.resolve();a.m.info(function(){return"Stopping streaming for "+Xx(a)+"."});a.w&&(Tx.rtpStream.onError.removeListener(a.w),a.w=null);if(a.l){var c=a.l.wg();a.l=null}else c=Promise.resolve();return c.then(function(){a.b&&(Tx.rtpStream.stop(a.b),Tx.rtpStream.destroy(a.b),a.b=null);a.f&&(Tx.rtpStream.stop(a.f),Tx.rtpStream.destroy(a.f),a.f=null);a.o&&(Tx.udpTransport.destroy(a.o),a.o=null);a.Aa();
a.m.info(function(){return"Stopped streaming for "+Xx(a)+"."});a.g=null;a.j=null;Sx(b,1)})})};
var cy=function(a,b){var c=JSON.stringify(b);return Promise.all([a.b&&new Promise(function(b){return Tx.rtpStream.getRawEvents(a.b,c,b)}),a.f&&new Promise(function(b){return Tx.rtpStream.getRawEvents(a.f,c,b)})]).catch(function(b){a.m.error("Unexpected error when calling getRawEvents()",b);return[]}).then(function(a){return new Blob(a.filter(function(a){return!!a}),{type:"application/gzip"})})},dy=function(a){return Promise.all([a.b&&new Promise(function(b){return Tx.rtpStream.getStats(a.b,b)}),a.f&&
new Promise(function(b){return Tx.rtpStream.getStats(a.f,b)})]).catch(function(b){a.m.error("Unexpected error when calling getStats()",b);return[]}).then(function(a){return Object.assign.apply(Object,[{}].concat(n(a.filter(function(a){return!!a}))))})},Xx=function(a){if(a.g&&a.j)var b="audio+video ";else if(a.g)b="audio-only ";else if(a.j)b="video-only ";else return"stopped";return a.g instanceof Wx||a.j instanceof Wx?b+"remoting":b+"streaming"},Yx=function(a){return new Promise(function(b){var c=
function(c,e,f){c&&!a.g&&(Tx.rtpStream.destroy(c),c=null);e&&!a.j&&(Tx.rtpStream.destroy(e),e=null);a.m.info(function(){return"Created Cast Streaming session: audioStreamId="+c+", videoStreamId="+e+"."});a.b=c;a.f=e;a.o=f;b()};a.g instanceof Wx||a.j instanceof Wx?Tx.session.create(null,null,c):Tx.session.create(a.g,a.j,c)})};
Vx.prototype.C=function(){for(var a=bh(),b=bh(),c=[],d=k([this.b,this.f]),e=d.next();!e.done;e=d.next())if(e=e.value)for(var f=e==this.b,h=f?127:96,l=f?Math.floor(499999*Math.random())+1:Math.floor(499999*Math.random())+500001,t=f?48E3:9E4,u=k(Tx.rtpStream.getSupportedParams(e)),A=u.next();!A.done;A=u.next())A=A.value,A.payload.payloadType=h,A.payload.maxLatency=this.h.maxLatencyMillis,A.payload.minLatency=this.h.minLatencyMillis,A.payload.animatedLatency=this.h.animatedLatencyMillis,A.payload.ssrc=
l,A.payload.clockRate=t,A.payload.aesKey=a,A.payload.aesIvMask=b,f?(A.payload.channels=2,A.payload.maxBitrate=this.h.audioBitrate,A.payload.maxFrameRate=100):(A.payload.minBitrate=this.h.minVideoBitrate,A.payload.maxBitrate=this.h.maxVideoBitrate,A.payload.maxFrameRate=this.h.maxFrameRate),c.push(new ey(e,A));return c};
var ay=function(a,b,c){b&&!c.some(function(a){return a.Cf==b})&&(a.m.F("Destroying RTP stream not selected by the receiver: id="+b),Tx.rtpStream.destroy(b),b=null);return b},Zx=function(a,b){return new Promise(function(c,d){for(var e=[],f=0;f<b.length;++f){var h=b[f].params,l={index:f,codecName:h.payload.codecName.toLowerCase(),rtpProfile:"cast",rtpPayloadType:h.payload.payloadType,ssrc:h.payload.ssrc,targetDelay:h.payload.animatedLatency,aesKey:h.payload.aesKey,aesIvMask:h.payload.aesIvMask,timeBase:"1/"+
h.payload.clockRate,receiverRtcpEventLog:a.h.enableLogging,rtpExtensions:["adaptive_playout_delay"]};a.h.dscpEnabled&&(l.receiverRtcpDscp=46);127==h.payload.payloadType?Object.assign(l,{type:"audio_source",bitRate:0<h.payload.maxBitrate?1E3*h.payload.maxBitrate:60*h.payload.maxFrameRate+h.payload.clockRate*h.payload.channels,sampleRate:h.payload.clockRate,channels:h.payload.channels}):Object.assign(l,{type:"video_source",renderMode:"video",maxFrameRate:Math.round(1E3*h.payload.maxFrameRate)+"/1000",
maxBitRate:1E3*h.payload.maxBitrate,resolutions:[{width:a.h.maxWidth,height:a.h.maxHeight}]});e.push(l)}var t=a.g instanceof Wx||a.j instanceof Wx?"remoting":"mirroring",u={type:"OFFER",sessionId:a.H,seqNum:tk(a.G),offer:{castMode:t,receiverGetStatus:!0,supportedStreams:e}};a.m.info(function(){return"Sending OFFER message: "+JSON.stringify(u)});Lx(a.D,u,"ANSWER",1E4,function(b,e){if(null==b)d(e);else if("ok"==b.result&&b.b){if(b.f!=u.seqNum)return a.m.F("Ignoring ANSWER for OFFER with different seqNum: "+
JSON.stringify(b)),!1;((e=b.b.h)&&e!=t||!e&&"mirroring"!=t)&&a.m.error("Expected receiver to ANSWER with castMode="+t+", but got: "+e);kb(a.m,function(){return"Received ANSWER: "+JSON.stringify(b)});c(b.b)}else d(Error("Non-OK ANSWER received: "+JSON.stringify(b)));return!0})})},$x=function(a,b,c){if(b.b.length!=b.f.length)return a.m.error("sendIndexes.length != ssrcs.length in ANSWER: "+JSON.stringify(b)),[];for(var d=[],e={},f=0;f<b.b.length;e={candidate:e.candidate},++f){var h=b.b[f];if(0>h||h>=
c.length)return a.m.error("Receiver selected invalid index ("+h+" < "+c.length+") in ANSWER: "+JSON.stringify(b)),[];e.candidate=c[h];if(d.some(function(a){return function(b){return b.Cf==a.candidate.Cf}}(e)))return a.m.error("Receiver selected same RTP stream twice in ANSWER: "+JSON.stringify(b)),[];e.candidate.params.payload.feedbackSsrc=b.f[h];if(d.some(function(a){return function(b){return b.params.payload.feedbackSsrc==a.candidate.params.payload.feedbackSsrc}}(e)))return a.m.error("Receiver provided same SSRC for two different RTP streams in ANSWER: "+
JSON.stringify(b)),[];d.push(e.candidate)}return d},by=function(a,b,c){var d=null,e=function(){d&&(Tx.rtpStream.onStarted.removeListener(d),d=null)};return(new Promise(function(e,h){var f=b.j||2344;a.m.info(function(){return"Starting RTP streams to receiver at "+(a.u+":"+f)+(" for selected offers: "+JSON.stringify(c))});var t=a.o||-1;a.h.dscpEnabled&&(a.m.info("Enabled DSCP in sender."),Tx.udpTransport.setOptions(t,{DSCP:!0}));Tx.udpTransport.setDestination(t,{address:a.u,port:f});var u=new Set(c.map(function(a){return a.Cf}));
d=function(a){u.delete(a);0==u.size&&e()};Tx.rtpStream.onStarted.addListener(d);t=k(c);for(var A=t.next();!A.done;A=t.next())A=A.value,Tx.rtpStream.toggleLogging(A.Cf,a.h.enableLogging),Tx.rtpStream.start(A.Cf,A.params);setTimeout(function(){h(Error("Timeout: RTP streams failed to start."))},1E4)})).then(e).catch(function(a){e();throw a;})},Ux=function(a,b,c){var d=this;return a&&b in a?function(){try{a[b](c)}catch(e){d.m.error("Error from testHooks."+b,e)}}:function(){}},ey=function(a,b){this.Cf=
a;this.params=b},Wx=function(){};var hy=function(a,b,c,d,e,f){this.w=a;this.D=fy(b,this.w.xb);this.G=new Vx(this.w.xb,c,d,e,f);this.A=e;this.j=new Mx;this.h=new gy;this.B=new mojo.Binding(mojo.MirrorServiceRemoter,this,null);this.m=db("mr.mirror.cast.MediaRemoter");this.u=this.b=this.l=this.g=this.C=null;this.f=!0;this.o=this.H.bind(this)};
hy.prototype.Wa=function(a,b){var c=this;return Ox(this.j,1,function(d){c.C=a;c.g=b;var e=c.B.createInterfacePtrAndBind();c.B.setConnectionErrorHandler(function(){c.m.info("Remoter mojo pipe connection error.");iy(c)});c.b=new mojo.MirrorServiceRemotingSourcePtr;var f=tg(c.w.mediaSource||"");if(!f)throw Error("Failed to parse tab ID from source:\n          "+c.w.mediaSource);c.m.info("Connecting remoter to browser: tabId="+f);($f.get("mr.ProviderManager")||null).onMediaRemoterCreated(f,e,mojo.makeRequest(c.b));
c.b.ptr.setConnectionErrorHandler(function(){c.m.info("RemotingSource mojo pipe connection error.");iy(c)});return jy(c).then(function(){if(c.f)c.b.onSinkAvailable(c.D);Sx(d,2)})})};
var iy=function(a){return Qx(a.j,function(b){a.b&&(a.b.ptr.reset(),a.b=null);var c=a.l;a.l=null;a.g=null;a.C=null;a.B.close();chrome.settingsPrivate.onPrefsChanged.hasListener(a.o)&&chrome.settingsPrivate.onPrefsChanged.removeListener(a.o);return new Promise(function(d){window.setTimeout(function(){ky(a).then(function(){Sx(b,1);d();c&&c()})},250)})})};hy.prototype.wq=function(a){ly(this.h,a)};hy.prototype.sendMessageToSink=hy.prototype.wq;hy.prototype.Pf=function(a){this.g&&this.g.Pf(a)};
hy.prototype.wg=function(){return this.g?this.g.wg():Promise.resolve()};hy.prototype.Be=function(a,b){this.m.error("Error during streaming: "+a,b);if(this.b)this.b.onError();iy(this)};
hy.prototype.start=function(){var a=this,b=!1;this.m.info(function(){b=!0;return"Starting next media remoting session."});b&&my(this.h,function(b){return a.m.info(b)});ny(this.h);Ox(this.j,2,function(b){return(0,a.C)().then(function(c){a.l=c;Jx(a.A,"RPC",function(b){if(b.rpc){var c=a.h;b=b.rpc;c.l&&(++c.w,c.f+=b.length,c.l(b))}});Sx(b,3)}).catch(function(c){return ky(a).then(function(){Sx(b);throw c;})})}).then(function(){a.m.info("Remoting started successfully.")}).catch(function(b){a.m.error("Failed to start remoting",
b);a.b.onError()})};hy.prototype.start=hy.prototype.start;
hy.prototype.Lq=function(a,b){var c=this;return Ox(this.j,3,function(d){return c.G.start(a?new Wx:null,b?new Wx:null,c).then(function(a){oy(c.h,function(a){return c.A.sendMessage(a)},function(a){c.b.onMessageFromSink(a)});Sx(d,4);return{audio_stream_id:a.Zn||-1,video_stream_id:a.Sq||-1}}).catch(function(a){return ky(c).then(function(){Sx(d);throw a;})})}).catch(function(a){c.m.error("Failed to start remoting streams",a);iy(c);return{audio_stream_id:-1,video_stream_id:-1}})};
hy.prototype.startDataStreams=hy.prototype.Lq;hy.prototype.stop=function(a){var b=this;Px(this.j,function(c){b.b.onStopped(a);return ky(b).then(function(){b.m.info("Remoting stopped.");Sx(c,5);(0,b.l)().then(function(){return Ox(b.j,5,function(a){if(b.b&&b.f)b.b.onSinkAvailable(b.D);Sx(a,2);return Promise.resolve()})}).catch(function(a){throw a;});b.l=null})}).catch(function(a){b.m.error("Failed to stop remoting: ",a);iy(b)})};hy.prototype.stop=hy.prototype.stop;
hy.prototype.po=function(){null===this.u&&(this.u=ve(this.w.xb.rg).then(function(a){return a.f||!1}));return this.u.then(function(a){return{rate:(a?1E7:5E6)/8}})};hy.prototype.estimateTransmissionCapacity=hy.prototype.po;
var ky=function(a){return a.G.stop().then(function(){Kx(a.A,"RPC");py(a.h);qy(a.h)})},jy=function(a){return new Promise(function(b){chrome.settingsPrivate.getPref("media_router.media_remoting.enabled",function(c){chrome.runtime.lastError?a.m.error("Encountered error getting media remoting pref: "+JSON.stringify(chrome.runtime.lastError)):c.type!=chrome.settingsPrivate.PrefType.BOOLEAN?a.m.error("Pref value not a boolean: "+JSON.stringify(c)):(a.f=!!c.value,a.m.info("Initializing mediaRemotingEnabled_ with value read from pref: "+
a.f));chrome.settingsPrivate.onPrefsChanged.hasListener(a.o)||chrome.settingsPrivate.onPrefsChanged.addListener(a.o);b()})})};
hy.prototype.H=function(a){if(this.b){a=k(a);for(var b=a.next();!b.done;b=a.next())if(b=b.value,"media_router.media_remoting.enabled"==b.key){if(b.type!=chrome.settingsPrivate.PrefType.BOOLEAN){this.m.error("Pref value not a boolean: "+JSON.stringify(b));break}a=!!b.value;if(this.f==a)break;this.f=a;this.m.info("mediaRemotingEnabled_ changed to: "+this.f);if(this.f)this.b.onSinkAvailable(this.D);else this.b.onStopped(mojo.RemotingStopReason.USER_DISABLED);break}}};
var fy=function(a,b){var c=this,d=new mojo.RemotingSinkMetadata;d.features=[];d.friendly_name=b.Kq||"";d.audio_capabilities=[];d.video_capabilities=[];var e=mojo.RemotingSinkAudioCapability,f=mojo.RemotingSinkVideoCapability,h=d.audio_capabilities,l=d.video_capabilities,t=b.Ie||"";(a.b||[]).forEach(function(a){switch(a){case "audio":h.push(e.CODEC_BASELINE_SET);break;case "aac":h.push(e.CODEC_AAC);break;case "opus":h.push(e.CODEC_OPUS);break;case "video":l.push(f.CODEC_BASELINE_SET);break;case "4k":l.push(f.SUPPORT_4K);
break;case "h264":l.push(f.CODEC_H264);break;case "vp8":l.push(f.CODEC_VP8);break;case "vp9":t.startsWith("Chromecast Ultra")&&l.push(f.CODEC_VP9);break;case "hevc":t.startsWith("Chromecast Ultra")&&l.push(f.CODEC_HEVC);break;default:c.m.info("Unknown mediaCap name: "+a)}});b.Ie&&"Chromecast Ultra"==b.Ie&&l.push(f.SUPPORT_4K);return d},gy=function(){this.l=this.j=this.b=null;this.u=this.f=this.w=this.h=this.o=0;this.g=null},ny=function(a){a.b=[];ry(a,performance.now())},oy=function(a,b,c){a.j=b;a.l=
c;a.b?(b=a.b,a.b=null,b.forEach(function(b){return ly(a,b.data).then(b.yq,b.Fl)})):ry(a,performance.now())},py=function(a){if(a.b){var b=Error("Stop before delivering pending message");a.b.forEach(function(a){return a.Fl(b)});a.b=null}a.j=null;a.l=null},ly=function(a,b){if(a.j){var c=btoa(String.fromCharCode.apply(null,b));++a.o;a.h+=b.length;return a.j({type:"RPC",rpc:c})}return a.b?new Promise(function(c,e){a.b.push({data:b,yq:c,Fl:e})}):Promise.reject(Error("RPC pipe not started"))},my=function(a,
b){qy(a);a.g=setInterval(function(){if(a.b)var c=a.b.length+" messages are waiting to send.";else{c=performance.now();var d=(c-a.u)/1E3;d="Over the past "+d.toFixed(1)+" seconds, sent "+(a.o+" messages ("+Math.round(a.h/d)+" bytes/sec) and ")+("received "+a.w+" messages ("+Math.round(a.f/d)+" ")+"bytes/sec).";ry(a,c);c=d}b(c)},3E4)},qy=function(a){null!=a.g&&(clearInterval(a.g),a.g=null)},ry=function(a,b){a.o=0;a.h=0;a.w=0;a.f=0;a.u=b};var sy=function(a){return a&&a.getAudioTracks()&&0<a.getAudioTracks().length?a.getAudioTracks()[0]:null},ty=function(a){return a&&a.getVideoTracks()&&0<a.getVideoTracks().length?a.getVideoTracks()[0]:null};var uy=function(a,b,c,d,e){this.h=new Vx(a,b,c,d,void 0===e?null:e);this.m=db("mr.mirror.cast.MediaStreamer");this.j=new Mx;this.g=this.f=this.b=this.l=null};uy.prototype.start=function(a,b){var c=this;return Ox(this.j,1,function(d){c.l=a;c.b=sy(a);c.b&&"ended"==c.b.readyState&&(c.b=null);c.f=ty(a);c.f&&"ended"==c.f.readyState&&(c.f=null);if(!c.b&&!c.f)return Sx(d),Promise.reject(Error("No MediaStream tracks to stream."));c.g=b;return c.h.start(c.b,c.f,c.g).then(function(){return Sx(d,2)})})};
uy.prototype.stop=function(){var a=this;return Qx(this.j,function(b){return a.h.stop().then(function(){a.b=null;a.f=null;a.l=null;a.g=null;Sx(b,1)})})};var vy=function(a){return Ox(a.j,2,function(b){a.m.info("Suspending media streaming...");return a.h.stop().then(function(){a.m.info("Suspended media streaming.");Sx(b,3)})})};
uy.prototype.resume=function(){var a=this;return Ox(this.j,3,function(b){a.b&&"ended"==a.b.readyState&&(a.b=null);a.f&&"ended"==a.f.readyState&&(a.f=null);if(!a.b&&!a.f)return Promise.reject(Error("Cannot resume: All tracks have ended."));a.m.info("Resuming media streaming...");return a.h.start(a.b,a.f,a.g).then(function(){a.m.info("Resumed media streaming.");Sx(b,2)})})};var wy=function(a,b,c){this.j=a;this.g=b;this.h=c;this.m=db("mr.mirror.cast.WifiStatusMonitor");this.b=null;this.f=[]};wy.prototype.start=function(){var a=this;null==this.b&&(kb(this.m,"Starting Wifi Status Monitoring."),this.f=[],Jx(this.h,"STATUS_RESPONSE",function(b){return xy(a,b)}),this.b=setInterval(function(){return yy(a)},12E4),yy(this))};wy.prototype.stop=function(){null!=this.b&&(kb(this.m,"Stopping Wifi Status Monitoring."),clearInterval(this.b),this.b=null,Kx(this.h,"STATUS_RESPONSE"))};
var xy=function(a,b){if(null!=a.b)if(b.status){var c={};null!=b.status.b&&(c.wifiSnr=b.status.b);null!=b.status.f&&(c.wifiSpeed=b.status.f[3]);0==Object.keys(c).length?a.m.F(function(){return"No status fields populated in response: "+JSON.stringify(b)}):(c.timestamp=Date.now(),30==a.f.length&&a.f.shift(),a.f.push(c),a.m.info(function(){return"Current Wifi status: "+JSON.stringify(c)}))}else a.m.F(function(){return"Ignoring response without status: "+JSON.stringify(b)})},yy=function(a){a.h.sendMessage({type:"GET_STATUS",
sessionId:a.j,seqNum:tk(a.g),get_status:["wifiSnr","wifiSpeed"]})};var zy=function(a,b,c,d){this.D=b.rg;this.w={extVersion:chrome.runtime.getManifest().version,extChannel:"public",mirrorSettings:Jg(a),sender:navigator.userAgent||"UNKNOWN",receiverProductName:b.Ie};this.C=c;this.A=d;this.g=this.f=this.o=this.l=this.j=this.u=this.h=null;this.b=[]};zy.prototype.Pf=function(a){null!=this.f&&clearInterval(this.f);this.h=a;this.u=Date.now();this.f=setInterval(this.B.bind(this,a),9E5)};
zy.prototype.wg=function(){null!=this.f&&(clearInterval(this.f),this.f=null);if(null!=this.h){var a=this.B(this.h);this.h=null;return a}return Promise.resolve()};zy.prototype.Be=function(a,b){null==this.j&&(this.j=Date.now(),"function"===typeof a?this.l=a():"string"===typeof a&&(this.l=a),b&&"string"===typeof b.stack&&(this.o=b.stack))};
var By=function(a,b){return(null==a.h?Promise.resolve():a.B(a.h)).then(function(){var c=b.map(function(b){b=Ay(a,b);var c=b.map(function(a){return a.events}).filter(function(a){return null!=a}),d=["["];b.map(function(a){return a.Bf}).forEach(function(a,b){0<b&&d.push(",");d.push(a)});d.push("]");return{events:new Blob(c,{type:"application/gzip"}),Bf:new Blob(d,{type:"application/json"})}});a.b=[];return c})};
zy.prototype.B=function(a){var b=this;if(null!=this.g)return this.g;var c=ve(this.D).then(function(c){c={receiverVersion:c.b,receiverConnected:c.g,receiverOnEthernet:c.f,receiverHasUpdatePending:c.h,receiverUptimeSeconds:c.j};Object.assign(c,b.w);var d=Date.now();Object.assign(c,{startTime:b.u,endTime:d,activity:Xx(a),receiverWifiStatus:Array.from(b.A.f)});b.u=d;null!=b.j&&(Object.assign(c,{streamingErrorTime:b.j,streamingErrorMessage:b.l,streamingErrorCause:b.o}),b.j=null,b.l=null,b.o=null);return c});
return(this.g=Promise.all([c.then(function(b){return cy(a,b)}),c,dy(a)]).then(function(a){var c=k(a);a=c.next().value;var d=c.next().value;c=c.next().value;b.b.push({events:a,Bf:new Blob([JSON.stringify(Object.assign({tags:d},c))],{type:"application/json"})});b.b=Ay(b,b.C);b.g=null}))||Promise.resolve()};
var Ay=function(a,b){b-=2;for(var c=[],d=a.b.length-1;0<=d;--d){b-=a.b[d].Bf.size+1;if(0>b)break;c.push({events:null,Bf:a.b[d].Bf});if(null!=a.b[d].events){var e=a.b[d].events.size;b>=e&&(c[c.length-1].events=a.b[d].events,b-=e)}}return c.reverse()};var Cy=db("mr.NetworkUtils"),Dy=function(a,b){return Lf?new Promise(function(c,d){chrome.networkingPrivate.setWifiTDLSEnabledState(a,b,function(a){chrome.runtime.lastError?(Cy.F("Unable to set TDLS state: state = "+b+", error = "+chrome.runtime.lastError.message),d("Unable to set TDLS state to "+b+".")):(Cy.info("TDLS state changed: state = "+b+", status = "+a),c(a))})}):Promise.reject("TDLS feature not enabled.")};var Ey=function(a,b,c,d){d=void 0===d?null:d;Gg.call(this,b);var e=b.xb;this.B=e.sessionId;this.D=e.rg;this.C=a;this.H=d;this.m=db("mr.mirror.cast.Session");this.o=new Mx;this.w=new sk("mirror.cast.SeqNumGenerator");this.l=new Ix(b.id);this.j=new uy(e,this.C,this.w,this.l,this.H);this.g=null;this.b=new zy(a,e,c,new wy(this.B,this.w,this.l));this.f=!1;this.A=null};m(Ey,Gg);g=Ey.prototype;
g.start=function(a){var b=this;return Ox(this.o,1,function(c){var d=new ob("MediaRouter.CastStreaming.Session.Launch");return Fy(b).then(function(c){b.f=c;return b.j.start(a,b)}).then(function(){if(b.j.h.A){var a=b.b;a.w.tdlsIsOn=b.f;a.A.start();Gy(b)}else b.b.w.tdlsIsOn=b.f;d.b();b.A=new ub("MediaRouter.CastStreaming.Session.Length");Sx(c,2);return b})})};
g.stop=function(){var a=this;return Qx(this.o,function(b){a.A&&(a.A.b(),a.A=null);a.b.A.stop();return a.j.stop().then(function(){return a.g?iy(a.g):Promise.resolve()}).then(function(){a.g=null;return a.f?Hy(a):Promise.resolve()}).then(function(){a.f=!1;Sx(b,4)})})};g.Dl=function(){var a={sessionId:this.B,seqNum:tk(this.w),type:"PRESENTATION",icons:[],title:Eg(this.ac)};this.m.info("Sending session metadata update to receiver: "+this.B);this.l.sendMessage(a)};g.Pf=function(a){this.b.Pf(a)};g.wg=function(){return this.b.wg()};
g.Be=function(a,b){this.b.Be(a,b);this.m.error(a,b);this.stop()};
var Iy=function(a,b){return By(a.b,b)},Fy=function(a){return a.C.useTdls?Dy(a.D,!0).then(function(b){if("Connected"==b)return a.m.info("Successfully enabled TDLS."),!0;a.m.F("Did not enable TDLS: result="+b);return!1}).catch(function(b){a.m.F("Error while calling enableTDLS()",b);return!1}):Promise.resolve(!1)},Hy=function(a){return Dy(a.D,!1).catch(function(b){return a.m.error("Error while turning TDLS back off",b)})},Gy=function(a){Jy(a).then(function(b){(b.b||[]).includes("video")?Ky(a,b):a.m.F(function(){return"Receiver incapable of Media Remoting: "+
JSON.stringify(b)})}).catch(function(b){a.m.F("None/Invalid capabilites response. Media Remoting disabled.",b)})},Jy=function(a){return new Promise(function(b,c){var d={type:"GET_CAPABILITIES",sessionId:a.B,seqNum:tk(a.w)};a.m.info(function(){return"Sending GET_CAPABILITIES message: "+JSON.stringify(d)});Lx(a.l,d,"CAPABILITIES_RESPONSE",3E4,function(e,f){if(null==e)return c(f),!0;if("ok"!=e.result||!e.capabilities)return c(Error("Bad response: "+JSON.stringify(e))),!0;if(e.f!=d.seqNum)return a.m.info(function(){return"Ignoring CAPABILITIES_RESPONSE with different seqNum: "+
JSON.stringify(e)}),!1;kb(a.m,function(){return"Received CAPABILITIES_RESPONSE: "+JSON.stringify(e)});b(e.capabilities);return!0})})},Ky=function(a,b){Ox(a.o,2,function(c){var d=a.h.xb.Ie||"<UNKNOWN>";if(!d.startsWith("Chromecast")&&!d.startsWith("Eureka Dongle"))return a.m.F("HACK: Media Remoting disabled because the receiver model--"+('"'+d+'" according to discovery--is not a Chromecast.')),Sx(c),Promise.resolve();a.g=new hy(a.h,b,a.C,a.w,a.l,a.H);return a.g.Wa(a.M.bind(a),a).catch(function(b){a.m.error("Media Remoting start failed: "+
b.message,b)}).then(function(){return Sx(c)})})};Ey.prototype.M=function(){var a=this;return Ox(this.o,2,function(b){return new Promise(function(c,d){vy(a.j).then(function(){Sx(b,3);a.G=!0;Bg(a);c(a.Aa.bind(a))}).catch(function(b){a.Be("Failed to suspend MediaStreamer before starting remoting",b);d(b)})})})};
Ey.prototype.Aa=function(){var a=this;return Ox(this.o,3,function(b){return new Promise(function(c,d){a.j.resume().then(function(){Sx(b,2);a.G=!1;Bg(a);c()}).catch(function(b){a.Be("Failed resume MediaStreamer after ending remoting mode",b);d(b)})})})};var Ly=function(){ug.call(this,"cast_streaming")};m(Ly,ug);g=Ly.prototype;g.getName=function(){return"cast_streaming"};g.Pg=function(a,b){return new Ey(a,b,20969472,null)};g.zh=function(){ix(0)};g.wh=function(){ix(1)};g.Wi=function(){ix(2)};g.xh=function(){xb("MediaRouter.CastStreaming.Session.End")};g.yh=function(a){yb("MediaRouter.CastStreaming.Start.Failure",a,Hf)};g.og=function(){xb("MediaRouter.CastStreaming.Stream.End")};
g.Wh=function(a){var b=this;return(new Promise(function(a){return chrome.metricsPrivate.getIsCrashReportingEnabled(a)})).then(function(c){var d=c&&px(),e=[9351424];d&&e.push(20969472);return Iy(a,e).then(function(a){var e=a[a.length-1];a=nj(a[0].events).catch(function(a){b.L.error("Failed to persist events Blob.",a)});d&&0<e.events.size?lx(e.events,void 0,b.mp.bind(b)):c&&kx("stats.json",e.Bf,void 0,void 0);return a})})};g.mp=function(a){a&&(ox().b=Date.now())};
g.Gi=function(a){this.L.info("Received message to upload logs for "+a);return this.b?Iy(this.b,[20969472]).then(function(b){b=k(b).next().value;return 0==b.events.size?"":lx(b.events,a)}):Promise.resolve(My(this,a))};
var My=function(a,b){var c=window.localStorage.getItem("mr.temp.mirror.cast.Service.eventsBlob");if(null==c||1>c.length)c=null;else{for(var d=new Uint16Array(c.length),e=0;e<c.length;++e)d[e]=c.charCodeAt(e);c=d.buffer;d=(new Uint8Array(c,c.byteLength-1,1))[0];c=new Uint8Array(c,0,c.byteLength-(0==d?2:1));c=new Blob([c],{type:"application/gzip"})}if(null!=c&&0!=c.size)return nj(new Blob),a.L.info("Uploading saved logs for feedback."),lx(c,b)},Ny=new Ly;jg("mr.mirror.cast.Service",Ny);
